# ==============================================================================
# CONFIGURATION DEPLOIEMENT CERTIFICATS
# Structure :
# DOMAINE|ZONE_ID|TOKEN|SSH_USER@HOST|KEY_PATH|REMOTE_DIR|CMD
#
# Remarques :
# - KEY_PATH : Mettre "-" pour utiliser la clé par défaut contenue dans ce serveur
# - TOKEN/ZONE_ID : Mettre "-" sur les lignes secondaires (multi-cibles)
# ==============================================================================

# Exemple de commande à mettre dans votre contrab. (contrab -e)
#@weekly /root/certbot/deploy_manager.sh siteweb1.com
#@weekly /root/certbot/deploy_manager.sh siteweb2.com

# Veuillez à installer curl sur la machine (apt update && apt install -y curl)
# Vous pouvez envoyer vos certificats vers d'autres services, comme votre serveur de mail, etc.

# --- siteweb1.com ---
#DOMAINE|ZONE_ID|TOKEN|SSH_USER@HOST|KEY_PATH|REMOTE_DIR|CMD
siteweb1.com|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|root@IPPRIVEVPN|/root/.ssh/id_rsa|/root/reverseproxy/domains/siteweb1.com/certs|docker restart web
siteweb1.com|-|-|root@IPPRIVEVPN|/root/.ssh/id_rsa|/root/autrechemin/domains/siteweb1.com/certs|docker compose restart

# --- siteweb2.com ---
#DOMAINE|ZONE_ID|TOKEN|SSH_USER@HOST|KEY_PATH|REMOTE_DIR|CMD
siteweb2.com|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|root@IPPRIVEVPN|/root/.ssh/id_rsa|/root/reverseproxy/domains/siteweb1.com/certs|docker restart web
